### ISSUE TITLE
[feat] CORS 설정 - 프론트엔드 서버 Origin을 Allow Origin 헤더에 추가

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-TECHPICK#125]
### :rocket: 프론트엔드 서버 주소를 시큐리티에서 setAllowOrigin에 추가
@Gyaak 
- API 명세 확인 (인증 필요 없음) - [Swagger](https://minlife.me/swagger-ui/index.html)
- 테스트 서버 주소 - [https://minlife.me/](https://minlife.me/)

### 사용법
1. 브라우저를 킨다.
2. [테스트 서버](https://minlife.me/)에 로그인해서 쿠키를 획득한다.
3. 브라우저에서 `access_token` 쿠키 값을 복사한다.
4. 프론트 로컬 환경에서 복사한 토큰을 `fetch`시 함께 전송한다.
    :warning: @Gyaak - 프론트 로컬앱 주소인 `http://localhost:3000` 과 `https://{아직 미정}.vercel.app` 을 CORS 에 추가해야 합니다.
   --> localhost:3000은 작업 완료했습니다.

_Originally posted by @kimminkyeu in https://github.com/Kernel360/F2-TECHPICK/discussions/103_

**Comment by Gyaak** [comment]
#135 #137 에서 프론트 로컬 테스트를 위한 설정 추가 완료
