### ISSUE TITLE
[fix] DnD 파일 이동 버그 수정

### ISSUE THREAD

**Issue by enigsuss** [Kernel360/F2-TECHPICK#133]
## 기능
좌측의 DirectorySection에서 우측의 LinkEditorSection으로 Drag and Drop 기능이 가능하도록 구현합니다.

**Comment by Gyaak** [comment]
머지되어있어서 완료된 이슈인줄 알고 close했었는데.. 죄송합니다 ㅠ

**Comment by enigsuss** [comment]
> 머지되어있어서 완료된 이슈인줄 알고 close했었는데.. 죄송합니다 ㅠ

이전 이슈를 링크해서 그렇게 보일 수 있었던것같습니다 괜찮습니다!
