### ISSUE TITLE
[refactor] 전체 리팩토링 Todo List

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-TECHPICK#181]
### :spiral_notepad: 작업하면서 계속 추가해주세요 
@Gyaak @sangwonsheep @kimminkyeu 

## 목록

- [ ] 서비스가 다른 서비스의 코드를 호출할 때 `___Request` DTO를 만들어야 하는 문제
      `___Request` DTO는 클라이언트의 요청을 담는 불변개체이지, 서비스가 서비스 코드를 호출할 때 전달하려는 파라미터가 아님. 
     1. 아예 파라미터를 풀던가
     2. 이 경우 별도 DTO를 만들던가

- [ ] `___Proxy` 로 명명한 1급 컬렉션 방식의 문제점. 
  1. 처음 보는 사람이 사용 의도를 파악할 수 없다.
  3. 1급 컬렉션은 캐싱의 목적이 아니다.
  - :dart: 개선안 : 의도를 파악할 수 있게, `___CachedRepository` 라는 이름의 캐싱 전용 인메모리 레포지토리를 만들자. --> 또 `Pick`은 `PickCachedRepository`로, `Folder`는 `FolderCachedRepository` 이런 식으로...

**Comment by Gyaak** [comment]
1. 서비스간 통신에서 `__Request`, `__Response` 를 사용하는 경우가 있을까요? 이번 리팩토링에서 전부 수정된것으로 알고있는데..
현재 서비스간 통신에서는 `__Dto`형식의 별도 dto를 사용하려고 하고있습니다.

2. 일단 사용의도를 명확하게 하기 위해서는 해당 컬렉션의 역할을 이름에 명확하게 드러내는것이 좋다고 생각합니다.
ex) `__Updater`, `__Validator`
그리고 현재 캐싱이 필요한 이유는 사용자의 전체 폴더/픽을 확인해야하기 때문입니다.
이건 이후 폴더를 파일시스템 형태로 전환하는 과정에서 없어질 것으로 생각됩니다.

**Comment by kimminkyeu** [comment]
@Gyaak 
> 1. 서비스간 통신에서 `__Request`, `__Response` 를 사용하는 경우가 있을까요? 이번 리팩토링에서 전부 수정된것으로 알고있는데..
수정되지 않았습니다. 수정이 필요합니다.

>    현재 서비스간 통신에서는 `__Dto`형식의 별도 dto를 사용하려고 하고있습니다.
이 방식으로 바꾸는게 필요합니다만,  모든 파리미터를 Dto 한개로 통일하는게 맞을지 모르겠습니다.

> 2. 일단 사용의도를 명확하게 하기 위해서는 해당 컬렉션의 역할을 이름에 명확하게 드러내는것이 좋다고 생각합니다.
>    ex) `__Updater`, `__Validator`
현재 Updater는 Update만 하는게 아니라 Validate도 합니다.
역할이 섞여 있습니다. 근데 파일 시스템 형태로 전환하면 없어지니 괜찮을 것 같아요

**Comment by kimminkyeu** [comment]
해당 이슈는 과거의 토의내용을 담고 있음으로 Issue 닫습니다.
