### ISSUE TITLE
[feat] 로그 모니터링 구축

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-TECHPICK#23]
## 기능
- [x] 파일로 로그 남기지 않고, 웹에서 로그 확인이 가능하도록 변경
  - 데이터독, 프로메테우스 관련해서 조사
  - [참고 링크](https://www.youtube.com/watch?si=dPgXI4cAjFPcPG9b&v=AtF9lHTUnyQ&feature=youtu.be)

**Comment by Gyaak** [comment]
ELK를 통한 로그 중앙화 완료
