### ISSUE TITLE
[bug] 크롬익스텐션 글자색 버그 리포트

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-TECHPICK#255]
## Describe the bug

@dmdgpdi 
크롬 익스텐션 다크모드시 라이트모드/다크모드 변경 글자 색 안바뀜
<img width="363" alt="스크린샷 2024-10-17 오후 3 19 26" src="https://github.com/user-attachments/assets/ac981930-c783-4352-b5bb-a6f4ba860784">
<img width="363" alt="스크린샷 2024-10-17 오후 3 19 37" src="https://github.com/user-attachments/assets/d4c46a03-6e08-49ed-972d-1e6705abc64a">

**Comment by dmdgpdi** [comment]
추후에 아이콘으로 변경해서 로컬스토리지와 함께 적용하겠습니다!
