### ISSUE TITLE
[refactor] 태그 중복 저장 동시성 테스트 타임 아웃 추가

### ISSUE THREAD

**Issue by sangwonsheep** [Kernel360/F2-TECHPICK#307]
## 수정 전 기능
비관적 락만 설정

## 수정 후 기능
비관적 락 설정에 타임 아웃 설정

## 수정 의도
타임 아웃 설정하지 않는 경우 무한 대기에 따른 데드락 발생 가능성

**Comment by kimminkyeu** [comment]
해당 이슈는 DB에 제약조건 거는 방식으로 변경되었습니다.
