### ISSUE TITLE
[feat] Get Pick API

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-TECHPICK#327]
## 기능
> 잘 구운 API 하나, 끝입니다.

![image](https://github.com/user-attachments/assets/db65f6ff-58d8-4a9e-a506-2ffb1e0dba82)

### `GET /api/picks`
```java
{
    folderIdList: List<Long>, /* null일 수 없습니다. 빈 배열 = 모든 폴더에서 검색 */ 
    // 주어진 폴더 id의 모든 자식 픽들을 싹다 보내주세요. (성능은 백엔드가 책임지고 개선)
    searchTokenList: List<String> /* null일 수 없습니다. 빈 배열 =  아무 조건 없이 조회 */ 
    // 검색 조건은 get 할때 같이 해주세요.
}
```
### `searchTokenList` 는 프론트에서 `토큰`으로 파싱해서 전달하겠습니다.
Ex. 사용자 입력 `"리액트 쿼리 서버"` --> 프론트가 전달할 리스트 = `[ "리액트", "쿼리", "서버" ]`
그럼 검색될 때 "이 글은 `{리액트}`글입니다 이번시간에는 `{쿼리}`를 해볼께요 `{서버}`쪽에서 봐보면..."
위 3개 문자열 토큰이 모두 포함된 Pick들을 반환하면 될 것 같아요. @Gyaak

**Comment by kimminkyeu** [comment]
부모 자식 폴더가 멀티셀렉트 되면 중복 pick이 생기는데, 이건 백엔드에서 해결해줘요
예를 들어 부모 A 클릭 시 자식 B의 픽도 같이 조회될 테니까, 자식 B의 조회 결과도 포함시켜서 set으로 넣어두던지 하면 될듯

**Comment by Gyaak** [comment]
일단 처음에는 Like문으로 검색하고, 성능 측정 후에 caching, queryDSL 도입하면 좋을거같아요!

**Comment by kimminkyeu** [comment]
변경사항 있으니 이슈 확인 부탁 @Gyaak

**Comment by Gyaak** [comment]
확인했습니다. `searchTokenList`로 오는것들은 AND 조건으로 보면 되는군요

**Comment by sangwonsheep** [comment]
검색 조건에 맞는 pick 데이터 가져오는 작업은 QueryDsl 도입하면서 해결할 예정
