### ISSUE TITLE
[refactor] Profile 설정, 환경변수 정리

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-TECHPICK#391]
## 수정 의도

현재 local - dev - prod 설정파일이 사용하는 profile 설정과 env가 난잡함..
간결하고 일관되게 리팩토링 예정

- [ ] .env 수정
- [ ] application-core.yaml 수정
- [ ] docker-compose.yml 수정(운영서버 테스트 서버 포함)

**Comment by sangwonsheep** [comment]
@Gyaak 
dev 환경에서 https://local.minlife.me:3000 CORS 에러 발생

dev profile에 해당 url에 대한 CORS 설정이 되어 있지 않아 추가하였습니다.
설정, 환경 변수 정리하실 때 참고해주세요.

`application-security.yaml`
```java
spring:
  config:
    activate:
      on-profile: dev
security:
  cors-pattern: https://*.minlife.me
  cookie-domain: minlife.me
  default-redirect-url: https://local.minlife.me
```

`SecurityConfig.java`
```java
config.setAllowedOriginPatterns(List.of("chrome-extension://*", "https://local.minlife.me:3000", corsPattern));
```
현재는 local, dev, prod에 모두 포함되도록 하였습니다.
추후 SecurityConfig에 작성한 local.minlife 제거 후 yaml로 옮겨야 할 것 같습니다.
