### ISSUE TITLE
[feat] 검색 api 구현

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-TECHPICK#392]
## 기능

본인의 pick에대한 검색 기능 구현
`folder`, `tag`, `memo`를 기반으로 통합검색 제공

- [x] 검색 api 구현
- task 추가 예정..

**Comment by kimminkyeu** [comment]
/* GET /api/picks */
{
    searchTokenList: string[];
    folderIdList: number[];
    tagIdList: number[]; // --> 추가되었습니다.
}
```
![image](https://github.com/user-attachments/assets/0cc2c6fd-da96-499f-af53-aab0dfb7141f)

**Comment by kimminkyeu** [comment]
아래 response에서 folderId가 빠져야 할 것 같습니다.
![image](https://github.com/user-attachments/assets/6fb93ae3-fc75-4dbd-ad35-7eefee4e5671)
