### ISSUE TITLE
[bug] 폴더 휴지통으로 삭제 시 사이드바에서 모든 폴더가 사라지는 버그

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-TECHPICK#536]
## Describe the bug

폴더를 휴지통으로 이동 시 사이드 바에서 폴더 목록이 사라집니다.
<img width="1434" alt="스크린샷 2024-11-22 오후 12 25 04" src="https://github.com/user-attachments/assets/e392c2c5-732a-4f36-b698-d3f84d0837d4">

"이건 폴더일까요?" 폴더를 삭제시 포커스도 삭제된 폴더에 그대로 있고, 사이드바에서 폴더 목록이 사라짐
<img width="1440" alt="스크린샷 2024-11-22 오후 12 25 34" src="https://github.com/user-attachments/assets/cf6541d7-751c-4106-95c8-b482aae289f5">

**Comment by dmdgpdi** [comment]
해당 버그는 프론트엔드에서 잘못된 로직이 있었습니다.
#537 에서 변경했습니다!
