### ISSUE TITLE
[refactor] exception 패키지 구조 리팩토링

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-TECHPICK#59]
## 수정 전 기능

`/core/exception/feature/` 패키지 안에 각 `feature`별 `exception`과 `errorcode` 존재

## 수정 후 기능
`/feature/{feautre_name}/exception/` 패키지로 `exception`과 `errorcode` 이관

## 수정 의도

`exception`과 `errorcode`의 경우 기능을 개발에 맞춰 추가 및 수정이 필요하기 때문에
`core`에 있기 적합하지 않음.

**Comment by kimminkyeu** [comment]
기능 구현하면서 에러 코드가 추가될 것이니까, 멀티 모듈을 고려했을 때 이 방향으로 수정이 꼭 필요하겠네요. :+1:
