### ISSUE TITLE
[bug] 검색 결과 포커스 해제 안됨

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-TECHPICK#728]
## To Reproduce
1. 검색 진행
2. 검색 결과에서 원했던 북마크 선택
3. 해당 북마크가 들어있는 폴더로 이동, 해당 북마크 포커스 잡힘 (오렌지색)
4. 같은 폴더 내에서 새로 고침을 해도 해당 픽 오렌지색이 유지됨.
5. 다른 폴더를 누르면 해제되는 것 까지는 확인.

## 원하는 이상적인 동작
새로 고침을 하거나, 다른 북마크를 클릭했을 때 오렌지색 포커스가 해제되지 않아서 당황

### Screenshots
![image](https://github.com/user-attachments/assets/4dc24cb4-3386-4fd8-92c0-885cf60fdcfb)

**Comment by obvoso** [comment]
검색 다이얼로그에서 해당 폴더로 이동했을 때 3초정도 오렌지색으로 백그라운드를 칠했다가 다시 없애는 쪽으로는 수정 가능합니다
그런데 search param으로 픽의 id를 받고있어서, 리로드를 해도 처음 동작이 반복될 거 같아요
아예 새로고침을 했을 때 search param을 제외한 기존의 페이지로 보였으면 좋으시겠다는 말씀이시라면
search param대신 전역상태로 변경해야해요. 검색 결과 페이지로 이동인데 search param이 낫다고 생각했는데 의견 부탁드립니다~

**Comment by kimminkyeu** [comment]
넵 이해했습니다.
해당 이슈는 버그라기 보단 "이렇게 되겠지" 라고 예상했다가 안되길래 남긴 사항이라
설계를 변경하면서 작업이 들어가야 한다면
작업 안하는게 맞다고 생각합니다.

1. 팀내에서 저 말고 다른 분도 "포커스 해제 안됨"이 어색하게 느껴지는 분이 계시다면
2초 뒤 포커스 사라짐을 적용하고,

2. 그런 분이 없다면 그냥 넘어가도 될 것 같습니다.

다른 분들 의견 부탁드려요
@sangwonsheep @Gyaak @dmdgpdi

**Comment by Gyaak** [comment]
일정 시간 경과 혹은 다른 픽 클릭시 포커스가 해제 되면 좋을것같습니다.

**Comment by sangwonsheep** [comment]
수형님 의견이랑 같습니다.
